# Generated by Django 4.0.2 on 2022-04-05 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Текст варианта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.CharField(max_length=500, verbose_name='Опрос'),
        ),
        migrations.AlterModelTable(
            name='choice',
            table='Choices',
        ),
        migrations.AlterModelTable(
            name='poll',
            table='Polls',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='webapp.choice', verbose_name='Вариант ответа')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='webapp.poll', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'Answers',
            },
        ),
    ]
